### PR TITLE
port to biscuit 2.0

### PR DESCRIPTION
**Pull request by Geal**

### CODE REVIEW

**Comment by divarvel** [comment]
Thanks! This does change the behaviour though (and not i a better way, I think): it requires the public key to be checked before displaying the biscuit contents. While _check-before-parse_ makes sense in automated settings, here when we type `biscuit inspect`, we want to see what's in it, regardless of a public key check.

**Comment by clementd-fretlink** [comment]
I have pushed a commit making sure the datalog contents are printed even when no public key is provided. They are still not displayed when the public key check fails, because of the way errors are handled. I'm not super happy with it, but that's for another PR, I guess.

I also added some emojis to improve the output a bit (but there are still things to be improved on the datalog output front)

**Comment by clementd-fretlink** [comment]
```
❯ biscuit inspect --raw-input ../biscuit/samples/v2/test13_block_rules.bc🙈 Public key check skipped 🔑
Authority block:
== Datalog ==
right("file1", "read");
right("file2", "read");

== Revocation id ==
893ff2daf44325f05849f581de561732094f14223d724202ce2f3d4058cead2ba238e4ef3a6b18f076f155e5e21ec30eded28f98d29979a39eb7f72da128a404

==========

Block n°1:
== Datalog ==
valid_date("file1") <- time($0), resource("file1"), $0 <= 2030-12-31T12:59:59+00:00;
valid_date($1) <- time($0), resource($1), $0 <= 1999-12-31T12:59:59+00:00, !["file1"].contains($1);
check if valid_date($0), resource($0);

== Revocation id ==
3189fe4ccec73777fcb0a63fb497c4391bc967c1cc02ec409ae19e7e30fd2bfeb2c309e67c615bcae986a0de15a1a21b5623ccdab5afe36c11c539ac7e475202

==========
```

```
❯ biscuit inspect --raw-input ../biscuit/samples/v2/test13_block_rules.bc --public-key acdd6d5b53bfee478bf689f8e012fe7988bf755e3d7c5152947abc149bc20189 
✅ Public key check succeeded 🔑
🙈 Datalog check skipped 🛡️
Authority block:
== Datalog ==
right("file1", "read");
right("file2", "read");

== Revocation id ==
893ff2daf44325f05849f581de561732094f14223d724202ce2f3d4058cead2ba238e4ef3a6b18f076f155e5e21ec30eded28f98d29979a39eb7f72da128a404

==========

Block n°1:
== Datalog ==
valid_date("file1") <- time($0), resource("file1"), $0 <= 2030-12-31T12:59:59+00:00;
valid_date($1) <- time($0), resource($1), $0 <= 1999-12-31T12:59:59+00:00, !["file1"].contains($1);
check if valid_date($0), resource($0);

== Revocation id ==
3189fe4ccec73777fcb0a63fb497c4391bc967c1cc02ec409ae19e7e30fd2bfeb2c309e67c615bcae986a0de15a1a21b5623ccdab5afe36c11c539ac7e475202

==========
```

**Comment by clementd-fretlink** [comment]
The blocks contents are now displayed before the checks, which is a bit more readable. This also means that the blocks contents are always displayed, even if the public key check fails

```
❯ biscuit inspect --raw-input ../biscuit/samples/v2/test13_block_rules.bc
Authority block:
== Datalog ==
right("file1", "read");
right("file2", "read");

== Revocation id ==
893ff2daf44325f05849f581de561732094f14223d724202ce2f3d4058cead2ba238e4ef3a6b18f076f155e5e21ec30eded28f98d29979a39eb7f72da128a404

==========

Block n°1:
== Datalog ==
valid_date("file1") <- time($0), resource("file1"), $0 <= 2030-12-31T12:59:59+00:00;
valid_date($1) <- time($0), resource($1), $0 <= 1999-12-31T12:59:59+00:00, !["file1"].contains($1);
check if valid_date($0), resource($0);

== Revocation id ==
3189fe4ccec73777fcb0a63fb497c4391bc967c1cc02ec409ae19e7e30fd2bfeb2c309e67c615bcae986a0de15a1a21b5623ccdab5afe36c11c539ac7e475202

==========

🙈 Public key check skipped 🔑
🙈 Datalog check skipped 🛡️
```

```
❯ biscuit inspect --raw-input ../biscuit/samples/v2/test13_block_rules.bc --public-key 1a46d0da212aa8f77bc39939dc04d254ab32da63c1f067d9b5048fa88819b4b6 --verify-with "time(2021-11-01T14:44:44Z); deny if true;"
Authority block:
== Datalog ==
right("file1", "read");
right("file2", "read");

== Revocation id ==
893ff2daf44325f05849f581de561732094f14223d724202ce2f3d4058cead2ba238e4ef3a6b18f076f155e5e21ec30eded28f98d29979a39eb7f72da128a404

==========

Block n°1:
== Datalog ==
valid_date("file1") <- time($0), resource("file1"), $0 <= 2030-12-31T12:59:59+00:00;
valid_date($1) <- time($0), resource($1), $0 <= 1999-12-31T12:59:59+00:00, !["file1"].contains($1);
check if valid_date($0), resource($0);

== Revocation id ==
3189fe4ccec73777fcb0a63fb497c4391bc967c1cc02ec409ae19e7e30fd2bfeb2c309e67c615bcae986a0de15a1a21b5623ccdab5afe36c11c539ac7e475202

==========

❌ Public key check failed 🔑
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Signature(InvalidSignature("signature error: Verification equation was not satisfied"))', src/main.rs:718:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
❯ biscuit inspect --raw-input ../biscuit/samples/v2/test13_block_rules.bc --public-key acdd6d5b53bfee478bf689f8e012fe7988bf755e3d7c5152947abc149bc20189 --verify-with "time(2021-11-01T14:44:44Z); deny if true;"
Authority block:
== Datalog ==
right("file1", "read");
right("file2", "read");

== Revocation id ==
893ff2daf44325f05849f581de561732094f14223d724202ce2f3d4058cead2ba238e4ef3a6b18f076f155e5e21ec30eded28f98d29979a39eb7f72da128a404

==========

Block n°1:
== Datalog ==
valid_date("file1") <- time($0), resource("file1"), $0 <= 2030-12-31T12:59:59+00:00;
valid_date($1) <- time($0), resource($1), $0 <= 1999-12-31T12:59:59+00:00, !["file1"].contains($1);
check if valid_date($0), resource($0);

== Revocation id ==
3189fe4ccec73777fcb0a63fb497c4391bc967c1cc02ec409ae19e7e30fd2bfeb2c309e67c615bcae986a0de15a1a21b5623ccdab5afe36c11c539ac7e475202

==========

✅ Public key check succeeded 🔑
❌ Datalog check failed 🛡️
```

**Pull request merged**
